### ISSUE TITLE
Fly tokenization with multiple streams

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#1030]
I can fine-tune with flying tokenization like this, 

```
train_loader:
  name: finetuning
  dataset:
    #hf_name: d0rj/OpenOrca-ru
    hf_name: parquet # assuming data files are json formatted
    hf_kwargs:
      data_dir: /data/hf-models/data/
    split: train
    max_seq_len: ${max_seq_len}
    allow_pad_trimming: false
    decoder_only_format: true
    packing_ratio: 9
    shuffle: true
    preprocessing_fn: preprocessing:preprocessing_ruorca
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: true
  timeout: 10
```

but can I use multiple datasets here, like `streams`? Or I can use `streams` only with already tokenized data?

**Comment by dakinggg** [comment]
yup, https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/finetune/gpt2-arc-easy-cpu-streaming-dataset.yaml and https://github.com/mosaicml/llm-foundry/blob/main/scripts/data_prep/convert_finetuning_dataset.py

**Comment by dakinggg** [comment]
are you using the latest version of foundry? and no, you can't mix pretrainining and finetuning data, although you can construct finetuning data that looks like pretraining data if you want.

**Comment by AnatoliiPotapov** [comment]
> are you using the latest version of foundry? and no, you can't mix pretrainining and finetuning data, although you can construct finetuning data that looks like pretraining data if you want.

This will work but with possible unwanted memorisation of system prompts with low variability from instruct data

**Comment by dakinggg** [comment]
what do you mean? you don't have to put a system prompt in

**Comment by germanjke** [comment]
> yup, https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/finetune/gpt2-arc-easy-cpu-streaming-dataset.yaml and https://github.com/mosaicml/llm-foundry/blob/main/scripts/data_prep/convert_finetuning_dataset.py

yes, you give me example when I need to define local/remote of mds tokenized data

but can I use fly tokenization like this?

```
train_loader:
  name: finetuning
  dataset:
    hf_name: parquet
    streams:
        FT_SET_1:
            hf_name: FT_SET_1 # assuming data files are json formatted
            hf_kwargs:
                data_dir: /data/FT_SET_1/data/
            split: train
            preprocessing_fn: preprocessing:preprocessing_ruorca
        FT_SET_2:
            hf_name: FT_SET_2 # assuming data files are json formatted
            hf_kwargs:
                data_dir: /data/FT_SET_2/data/
            split: train
            preprocessing_fn: preprocessing:preprocessing_ruorca
    max_seq_len: ${max_seq_len}
    allow_pad_trimming: false
    decoder_only_format: true
    packing_ratio: 9
    shuffle: true
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: true
  timeout: 10
```
