### ISSUE TITLE
How to fine-tune instruct mpt-7b model?

### ISSUE THREAD

**Issue by dydx-git** [mosaicml/llm-foundry#108]
I see in the `train.py` under `scripts/train`, it gets a model when given a model configuration. I took a look at this yaml `7b_dolly_sft.yaml` and do you think I could further tune the instruct model somehow? 

What name do I specify in the yaml for the instruct model? Or can I give it a custom path to that instruct model if I have saved it locally? Looking to freeze weights for all the layers other than the last one and then fine-tuning. 

Please guide me. Thanks a bunch!

**Comment by baptistejamin** [comment]
A solution was found here: https://github.com/mosaicml/llm-foundry/issues/94#issuecomment-1543394147

**Comment by alextrott16** [comment]
To set your starting model to our MPT-7B-Instruct model on the Hugging Face hub, you'd use this model config in your YAML
```yaml
  # Model
  model:
    name: hf_causal_lm
    pretrained_model_name_or_path: mosaicml/mpt-7b-instruct
    device: cpu
    pretrained: true
    # Comment the attn_config block to use default "torch" attention
    attn_config:
      attn_impl: triton
```
Note that `pretrained_model_name_or_path` determines what value is passed to Hugging Face's `AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path=...)` when building the model. `from_pretrained` supports local paths.

For freezing all the weights except the last layer, you can add some custom logic to `scripts/train/train.py`. The guy in [this video](https://www.youtube.com/watch?v=KSlWkrByc0o) does that freezing with our model inside a notebook. Might be a useful reference.
