### ISSUE TITLE
profiler issue

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#1448]
Hi, I'm experiencing an error when using the PyTorch profiler. I found same [issue](https://github.com/pytorch/pytorch/issues/113564) about torch profiler. My python version 3.11 and last MosaicML docker.

The issue occurs with the following profiler configuration in my code:

```
profiler:
  sys_prof_cpu: true
  sys_prof_memory: true
  sys_prof_disk: true
  sys_prof_net: true
  torch_prof_record_shapes: true
  torch_prof_profile_memory: true
  torch_prof_with_stack: true
  torch_prof_with_flops : true
  torch_prof_use_gzip: true
  torch_prof_overwrite: true
  torch_prof_remote_file_name: s3://my_bucket/path/torch_profiler/run_name_{run_name}_rank_{rank}_batch_{batch}_torch_profiler.pt.trace.json
  json_trace_handler:
    remote_file_name: s3://my_bucket/path/json_profiler/run_name_{run_name}_epoch_{epoch}_rank_{rank}_batch_{batch}_json_profiler.pt.trace.json
    overwrite: true
  schedule:
    wait: 0
    warmup: 0
    active: 1
    repeat: 0
```

```
[rank4]:   File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2345, in fit
[rank4]:     self._train_loop()
[rank4]:   File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2603, in _train_loop
[rank4]:     self.engine.run_event(Event.BATCH_END)
[rank4]:   File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 303, in run_event
[rank4]:     self._run_nonlogger_callbacks(event)
[rank4]:   File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 501, in _run_nonlogger_callbacks
[rank4]:     self._run_callbacks(event, callbacks)
[rank4]:   File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 493, in _run_callbacks
[rank4]:     cb.run_event(event, self.state, self.logger)
[rank4]:   File "/usr/lib/python3/dist-packages/composer/core/callback.py", line 96, in run_event
[rank4]:     return event_cb(state, logger)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/lib/python3/dist-packages/composer/profiler/torch_profiler.py", line 361, in batch_end
[rank4]:     self.profiler.step()
[rank4]:   File "/usr/lib/python3/dist-packages/torch/profiler/profiler.py", line 727, in step
[rank4]:     self._transit_action(prev_action, self.current_action)
[rank4]:   File "/usr/lib/python3/dist-packages/torch/profiler/profiler.py", line 744, in _transit_action
[rank4]:     action()
[rank4]:   File "/usr/lib/python3/dist-packages/torch/profiler/profiler.py", line 738, in _trace_ready
[rank4]:     self.on_trace_ready(self)
[rank4]:   File "/usr/lib/python3/dist-packages/composer/profiler/torch_profiler.py", line 280, in handler_fn
[rank4]:     prof.export_chrome_trace(trace_file_name)
[rank4]:   File "/usr/lib/python3/dist-packages/torch/profiler/profiler.py", line 212, in export_chrome_trace
[rank4]:     fout.writelines(fin)
[rank4]:   File "<frozen codecs>", line 322, in decode
```
