### ISSUE TITLE
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/llm-foundry#1484]
The full warning is as follows:
```
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. 
This might lead to unexpected behaviour
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in LlamaForCausalLM is torch.float32. 
You should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. 
Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2", torch_dtype=torch.float16)`
```

My yaml looks as follows:
```yaml
model:
  name: hf_causal_lm
  use_flash_attention_2: true
  pretrained: true
  pretrained_model_name_or_path: ${variables.model_name_or_path}
  use_auth_token: true
```
and `precision: amp_bf16`. Is this warning expected because we are loading in fp32? Is it okay to leave it as it is, or it has some non-obvious negative implications?
