### ISSUE TITLE
Unable to reproduce the benchmark

### ISSUE THREAD

**Issue by Infrastructure-dp** [mosaicml/llm-foundry#1706]
I am trying to reproduce the running results of mpt-7b on another server. I followed the parameters in the H100 80GB BF16 table in script/train/benchmarking and tested 7b on 8GPU, seqLen=2048. The rest of the cases are consistent with the table parameters, but I can only achieve **13.53% MFU**, which is far lower than the **46.44%** mentioned in the table. Is there something wrong with my settings?
Below is my yaml file and the running results

**yaml:**
```
variables:
  data_local: ./my-copy-c4
  data_remote:  # If blank, files must be present in data_local
  max_seq_len: 2048
  global_seed: 17

  # Run Name
  run_name:  # If left blank, will be read from env var $RUN_NAME

max_seq_len: ${variables.max_seq_len}
run_name: ${variables.run_name}

# Model
model:
  name: mpt_causal_lm
  init_device: meta
  d_model: 768
  n_heads: 12
  n_layers: 12
  expansion_ratio: 4
  max_seq_len: ${variables.max_seq_len}
  vocab_size: 50368
  attn_config:
    attn_impl: flash

# Tokenizer
tokenizer:
  name: /llm-foundry/model/gpt-neox-20b
  kwargs:
    model_max_length: ${variables.max_seq_len}

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${variables.data_local}
    remote: ${variables.data_remote}
    split: train
    shuffle: true
    max_seq_len: ${variables.max_seq_len}
    shuffle_seed: ${variables.global_seed}
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: ${variables.data_local}
    remote: ${variables.data_remote}
    split: val
    shuffle: false
    max_seq_len: ${variables.max_seq_len}
    shuffle_seed: ${variables.global_seed}
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 6.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 4800ba  # ~ 2.5B tokens
eval_interval: 500ba
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 48

# System
seed: ${variables.global_seed}
device_eval_batch_size: 16
device_train_microbatch_size: 6
# device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false                  
  activation_checkpointing_reentrant: false        
  activation_cpu_offload: false                    
  limit_all_gathers: true                          

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}
```

**result:**
```
[batch=2183/4800]:
         Train time/batch: 2182
         Train time/sample: 104736
         Train time/batch_in_epoch: 99
         Train time/sample_in_epoch: 4752
         Train time/token: 214499328
         Train time/token_in_epoch: 9732096
         Train memory/current_allocated_mem: 1.5557
         Train memory/current_active_mem: 1.5557
         Train memory/current_inactive_mem: 0.1556
         Train memory/current_reserved_mem: 25.1970
         Train memory/peak_allocated_mem: 13.5220
         Train memory/peak_active_mem: 13.6240
         Train memory/peak_inactive_mem: 2.6693
         Train memory/peak_reserved_mem: 25.1970
         Train memory/alloc_retries: 0
         Train trainer/device_train_microbatch_size: 6
         Train loss/train/total: 0.1101
         Train metrics/train/LanguageCrossEntropy: 0.1101
         Train metrics/train/LanguagePerplexity: 1.1163
         Train metrics/train/TokenAccuracy: 0.9773
         Train throughput/batches_per_sec: 11.1383
         Train throughput/samples_per_sec: 534.6373
         Train throughput/device/batches_per_sec: 1.3923
         Train throughput/device/samples_per_sec: 66.8297
         Train throughput/tokens_per_sec: 1094937.0966
         Train throughput/device/tokens_per_sec: 136867.1371
         Train throughput/flops_per_sec: 1071244129410935.2500
         Train throughput/device/flops_per_sec: 133905516176366.9062
         **Train throughput/device/mfu: 0.1353**
         Train time/train: 0.0571
         Train time/val: 0.0063
         Train time/total: 0.0634
         Train lr-DecoupledAdamW/group0: 0.0004
         Train time/remaining_estimate: 0.0767
```
