### ISSUE TITLE
Dynamic range of ALiBi

### ISSUE THREAD

**Issue by tginart** [mosaicml/llm-foundry#172]
ALiBi is awesome but I think there could be a potential issue with setting the dynamic range to 2^8 if we want context lengths into the 10-100k+ range (https://github.com/mosaicml/llm-foundry/blob/8edc590941c7bd9c0ea27e01fc8836d30b65c445/llmfoundry/models/layers/attention.py#LL535C5-L535C19).
 
I noticed that alibi_bias_max is set to 8 by default (as is standard in original ALiBi paper). It seems to me like a choice of ~16 could be better for the 10-100k+ range given 32 heads. Otherwise, don't we run the risk of too much attenuation based on context distance?

1. Is that the value that is used for the MPT-7B pretrain? 
2. Has anyone experimented with increasing this for long context fine-tuning? If not, at least any thoughts on doing so? (Clearly, changing this could "bork" the model, but perhaps it re-calibrates quickly if fine-tuning?)
3. Is there a way to change alibi_bias_max via yaml?

**Comment by samhavens** [comment]
Astute!

1. 8 was used for MPT-7B
2. Yes :smile: for the 65k fine tune we increased the ABM to 16 and it did adapt
3. Yes, example:

```yaml
  model:
    name: hf_causal_lm
    pretrained_model_name_or_path: mosaicml/mpt-7b
    pretrained: true
    config_overrides:
      max_seq_len: ${max_seq_len}
      attn_config:
        attn_impl: triton
        alibi: true
        alibi_bias_max: 16
```
