### ISSUE TITLE
Cannot reproduce benchmark results for mpt-7b-instruct when finetuning mpt-7b on dolly_hhrlhf

### ISSUE THREAD

**Issue by olaf-beh** [mosaicml/llm-foundry#383]
## Why do some evaluation results differ significantly when finetuning on dolly\_hhrlhf

I am comparing evaluation results for HF finetuned model **mosaicml/mpt-7b-instruct** with my own finetuned model based on **mosaicml/mpt-7b** using **mosiacml/dolly\_hhrlhf** from HF.

* I can reproduce benchmark results for mosaicml/mpt-7b (see first column in table below)
* Benchmark results for mosaicml/mpt-7b-instruct also look good (see second column, mosaicml didn't publish results as far as I know)
* Self finetuning using  mosiacml/dolly\_hhrlhf from HF for 3 and 1 epochs show significant differences. E,g, lambada\_openai is 0.680 for mosaicml/mpt-7b-instruct but for my own finetuning it is 0.024 (1 epoch) respectivelly 0.018 (3 epochs),

I would expect to be able to reproduce the evaluation results from **mosaicml/mpt-7b-instruct** HF model after finetuning **mosaicml/mpt-7b** LFM on **mosiacml/dolly\_hhrlhf** (so I am using only HF data, the pretrained model and training/finetuning data together with llm-foundary scripts). 

Can you shed some light on this? Do I have some mistake somewhere?

## Additional context

**Reproducing evaluations mpt-7b models** (all are from my own evaluation runs)

| model           | comment    | lambada_openai | hellaswag | piqa  | arc_easy | arc_challenge | boolq | copa  | winograd | winogrande | triviaqa | jeopardy |  mmlu |
| --------------- | ---------- | -------------- | --------- | ----- | -------- | ------------- | ----- | ----- | -------- | ---------- | -------- | -------- | ----- |
| mpt-7b          | HF         |          0.686 |     0.761 | 0.799 |    0.677 |         0.394 | 0.741 | 0.800 |    0.850 |      0.681 |    0.336 |    0.276 | 0.291 |
| mpt-7b-instruct | HF         |          0.680 |     0.768 | 0.801 |    0.686 |         0.432 | 0.739 | 0.830 |    0.846 |      0.676 |    0.328 |    0.301 | 0.342 |
| mpt-7b-instruct | self, 3ep  |          **0.018** |     **0.388** | 0.766 |    0.631 |         0.349 | **0.400** | 0.800 |    0.821 |      0.672 |    0.264 |    **0.086** | **0.239** |
| mpt-7b-instruct | self, 1ep  |         **0.024** |    **0.382** | 0.759 |    0.652 |         0.359 | **0.401** | 0.820 |    0.850 |      0.678 |    0.306 |    **0.141** | **0.236** |

Even when I only do 100ba (one epoch is 927ba for mosiacml/dolly\_hhrlhf) I get following results for benchmarks with highest differences:

| model           | comment     | lambada_openai | hellaswag | boolq | jeopardy |
| --------------- | ----------- | -------------- | --------- | ----- | -------- |
| mpt-7b-instruct | HF          |          0.680 |     0.768 | 0.739 |    0.301 |
| mpt-7b-instruct | self, 100ba |          0.023 |     0.384 | 0.398 |    0.019 |

My command for finetuning and evaluation:

```bash
composer train/train.py train/yamls/finetune/mpt-7b_dolly_sft.yaml
composer eval/eval.py eval/yamls/mpt7b_eval.yaml icl_tasks=eval/yamls/tasks-0-shot.yaml \
  load_path=mpt7b_dolly_sft/checkpoints/ep3-ba2781-rank0.pt
```

I used an slightly adapted `mpt-7b_dolly_sft.yaml` (removed comments and unimportant entries for brevity):

```yaml
max_seq_len: 2048
global_seed: 17

run_name: mpt7b_dolly_sft # If left blank, will be read from env var $RUN_NAME

model:
  name: hf_causal_lm
  pretrained: true
  pretrained_model_name_or_path: mosaicml/mpt-7b
  config_overrides:
    attn_config:
      attn_impl: triton
      attn_uses_sequence_id: false

# Tokenizer
tokenizer:
  name: mosaicml/mpt-7b
  kwargs:
    model_max_length: ${max_seq_len}

# Dataloaders
train_loader:
  name: finetuning
  dataset:
    hf_name: mosaicml/dolly_hhrlhf
    split: train
    max_seq_len: ${max_seq_len}
    allow_pad_trimming: false
    decoder_only_format: true
    shuffle: true
  drop_last: true
  num_workers: 8 # usually set this to the number of CPU cores in your machine divided by the number of GPUs.
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: true # Persisting workers will reduce the overhead of creating workers but will use some RAM
  timeout: 0

scheduler:
  name: linear_decay_with_warmup  # linear no warmup is HF default which dolly used
  t_warmup: 50ba  # add some warmup though, seems to help with MPT
  alpha_f: 0

optimizer:
  name: decoupled_adamw
  lr: 5.0e-6
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-8
  weight_decay: 0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 500ba  # 2-3 epochs seems like the sweet spot
```

My evaluation config `mpt7b_eval.yaml `:

```yaml
max_seq_len: 2048
tokenizer_name: EleutherAI/gpt-neox-20b
seed: 1
# precision: fp32
precision: amp_bf16

# Tokenizer
tokenizer:
  name: ${tokenizer_name}
  kwargs:
    model_max_length: ${max_seq_len}

# mpt-7b taken from train/yamls/pretrain/mpt-7b.yaml
model:
  name: mpt_causal_lm
  init_device: meta
  d_model: 4096
  n_heads: 32
  n_layers: 32
  expansion_ratio: 4
  max_seq_len: ${max_seq_len}
  vocab_size: 50432
  # vocab_size: 50368
  attn_config:
    attn_impl: triton

load_path: # mpt7b_dolly_sft/checkpoints/latest-rank0.pt # Add your (optional) Composer checkpoint path here!

device_eval_batch_size: 16

# FSDP config for model sharding
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: FULL
```

My `tasks-0-shot.yaml`:

```yaml
icl_tasks:
-
  label: jeopardy
  dataset_uri: eval/local_data/jeopardy_all.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: language_modeling
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
  has_categories: true
-
  label: lambada_openai
  dataset_uri: eval/local_data/lambada_openai.jsonl
  num_fewshot: [0]
  icl_task_type: language_modeling
-
  label: piqa
  dataset_uri: eval/local_data/piqa.jsonl  # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
-
  label: hellaswag
  dataset_uri: eval/local_data/hellaswag.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: multiple_choice
-
  label: arc_easy
  dataset_uri: eval/local_data/arc_easy.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
-
  label: arc_challenge
  dataset_uri: eval/local_data/arc_challenge.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
-
  label: copa
  dataset_uri: eval/local_data/copa.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: multiple_choice
-
  label: boolq
  dataset_uri: eval/local_data/boolq.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
-
  label: mmlu
  dataset_uri: eval/local_data/mmlu.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
  has_categories: true
-
  label: winograd
  dataset_uri: eval/local_data/winograd_wsc.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: schema
-
  label: winogrande
  dataset_uri: eval/local_data/winogrande.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: schema
-
  label: triviaqa
  dataset_uri: eval/local_data/triviaqa.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  icl_task_type: question_answering
```

**Comment by samhavens** [comment]
I think there are multiple things going on here, since that's a massive drop in lambada. However, could you pass on your `global_train_batch_size`?

**Comment by olaf-beh** [comment]
> However, could you pass on your global_train_batch_size?

Yes sure: `global_train_batch_size: 64`.
Here is also the missing part from `mpt-7b_dolly_sft.yaml` (I have been training with 8 gpus):

```yaml
max_duration: 3ep # 2-3 epochs seems like the sweet spot
eval_interval: 100ba # default 1ep
eval_first: true
global_train_batch_size: 64  # somewhere in the 6-8 * numgpus range seems good

# System
seed: ${global_seed}
device_eval_batch_size: 8
device_train_microbatch_size: 8
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: false
```
