### ISSUE TITLE
LORA + FSDP: ValueError: `FlatParameter` requires uniform `requires_grad`

### ISSUE THREAD

**Issue by minionKP** [mosaicml/llm-foundry#414]
## To reproduce

1. add lora configs to llm-foundry/scripts/train/finetune_example/mpt-7b-arc-easy--gpu.yaml
```
lora:
  args:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.05
    target_modules: ['Wqkv']
```

2. run composer train.py finetune_example/mpt-7b-arc-easy--gpu.yaml

## Expected behavior

FSDP + LORA fine-tuning 

## Config file

No other changes to example config file
