### ISSUE TITLE
FSDP hangs when calling self.generate() in eval_forward()  

### ISSUE THREAD

**Issue by mukhal** [mosaicml/llm-foundry#423]
## Environment 
I am using `torch==2.0.1` with CUDA 11.8

## Issue 
I am running multi-gpu training on a single node and my evaluation requires calling self.generate() inside eval_forward() the evaluation hangs and I get the error:
```
[Eval batch=1/90] Eval on eval data
[E ProcessGroupNCCL.cpp:828] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=423, OpType=_ALLGATHER_BASE, Timeout(ms)=600000) ran for 603606 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
```

My configuration is 
```
# Run Name
run_name: # If left blank, will be read from env var $RUN_NAME

# Model
model:
  name: hf_causal_lm
  pretrained_model_name_or_path: gpt2
  config_overrides:
    n_positions: ${max_seq_len}
  pretrained: false  # false: only use the architecture; true: initialize with pretrained weights

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: false

```

Things run smoothly when removing the self.generate() call. Any help is appreciated!
