### ISSUE TITLE
Streaming dataset with proportions works fine?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#426]
When i'm using `max_duration_time = 1ep` in `llm-foundry`, later in training, I will have progress bar like `[batch1 / X]` and etc, where `X` - total batchs in 1 epoch, calculated by `llm-foundry`

Let's create dataset with 2 subdatasets

```
train_loader:
  name: text
  dataset:
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
    cache_limit: 100gb
    streams:
        A:
          local: a
          proportion: 0.9
          remote: s3://a
          split: train
        B:
          local: a
          proportion: 0.1
          remote: s3://b
          split: train
```

why my `X` (total batches in trainloader) the **SAME** with different proportions? like 0.9 0.9, 0.9 0.1, 0.1 0.1. I guess its should be different

my `X` is different if i'm comment `B` dataset stream, its right

looks like `streaming` or `llm-foundry` have some bug?

@vchiley @karan6181 @codestar12 @knighton @abhi-mosaic
