### ISSUE TITLE
Not an issue, but a readme for integrating LLAMA2 pretraining with llm_foundry

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#479]
## Step 4:
- In terminal
   ```
   $pip install huggingface_hub
   $python3
   >>>from huggingface_hub import login
   >>>login()
   ---<Paste above created token here when prompted>---
   ```

## Step 5:
Go to ./llm-foundry/scripts/train/yamls/pretrain/
```
$cp opt-3b.yaml llama2-7b.yaml
```
Make following changes
```
# Model
model:
  name: hf_causal_lm
  pretrained_model_name_or_path: meta-llama/Llama-2-7b-hf
  init_device: meta
  pretrained: false
  use_auth_token: true

# Tokenizer
tokenizer:
  name: meta-llama/Llama-2-7b-hf
  kwargs:
    model_max_length: ${max_seq_len}
```

## Step 6: Run the usual composer command
```
$YAML_PATH=./llm-foundry/scripts/train/yamls/pretrain/llama2-7b.yaml''
composer -n 8 train.py $YAML_PATH train_loader.dataset.split=train_small eval_loader.dataset.split=val_small
```
