### ISSUE TITLE
Llamav2 eval.py "ValueError: The number of tokens in the tokenizer is greater than the number of tokens in the model"

### ISSUE THREAD

**Issue by es94129** [mosaicml/llm-foundry#490]
## Environment
```
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1040-azure-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100 80GB PCIe
Nvidia driver version: 470.103.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7V13 64-Core Processor
CPU family:                      25
Model:                           1
Thread(s) per core:              1
Core(s) per socket:              24
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        4890.87
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr rdpru arat umip vaes vpclmulqdq rdpid fsrm
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       768 KiB (24 instances)
L1i cache:                       768 KiB (24 instances)
L2 cache:                        12 MiB (24 instances)
L3 cache:                        96 MiB (3 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.25.1
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1
[pip3] torch-optimizer==0.3.0
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.0.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[pip3] triton-pre-mlir==2.0.0
[conda] Could not collect
```
## To reproduce

1. Create a small tasks yaml file `llm-foundry/scripts/eval/my_tasks.yaml`
```yaml
icl_tasks:
-
  label: mmlu
  dataset_uri: eval/local_data/world_knowledge/mmlu.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [10]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
  has_categories: true
```
2. Create an eval yaml file `llm-foundry/scripts/eval/hf_llamav2_7b_chat_eval.yaml`
```yaml
max_seq_len: 1024
seed: 1
precision: amp_fp16

model_name_or_path: meta-llama/Llama-2-7b-chat

models:
-
  model_name: ${model_name_or_path}
  model:
    name: hf_causal_lm
    pretrained_model_name_or_path: ${model_name_or_path}
    init_device: cpu
    pretrained: true
  tokenizer:
    name: ${model_name_or_path}
    kwargs:
      model_max_length: ${max_seq_len}

# load_path: # Add your (optional) Composer checkpoint path here!

device_eval_batch_size: 4

# FSDP config for model sharding
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: FULL

icl_tasks: '/local_disk0/llm-foundry/scripts/eval/my_tasks.yaml'
```
3. Run `composer eval/eval.py eval/hf_llamav2_7b_chat_eval.yaml` in `llm-foundry/scripts/`
```
Traceback (most recent call last):
  File "/local_disk0/llm-foundry/scripts/eval/eval.py", line 256, in <module>
    main(cfg)
  File "/local_disk0/llm-foundry/scripts/eval/eval.py", line 126, in main
    model_gauntlet_df) = evaluate_model(model_cfg, cfg.run_name,
  File "/local_disk0/llm-foundry/scripts/eval/eval.py", line 72, in evaluate_model
    composer_model = load_model(model_cfg.model, tokenizer, fsdp_config,
  File "/local_disk0/llm-foundry/scripts/eval/eval.py", line 37, in load_model
    raise e
  File "/local_disk0/llm-foundry/scripts/eval/eval.py", line 31, in load_model
    composer_model = COMPOSER_MODEL_REGISTRY[model_cfg.name](
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-e4e70166-2e94-40d7-acde-690d0c52988b/lib/python3.10/site-packages/llmfoundry/models/hf/hf_causal_lm.py", line 181, in __init__
    composer_model = super().__init__(model=model,
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-e4e70166-2e94-40d7-acde-690d0c52988b/lib/python3.10/site-packages/llmfoundry/models/hf/model_wrapper.py", line 50, in __init__
    super().__init__(model,
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-e4e70166-2e94-40d7-acde-690d0c52988b/lib/python3.10/site-packages/composer/models/huggingface.py", line 101, in __init__
    raise ValueError(
ValueError: The number of tokens in the tokenizer is greater than the number of tokens in the model. This would cause an error during training. You can resize the model embeddings to 32001 from 32000 by calling `model.resize_token_embeddings(len(tokenizer))` before calling the `HuggingFaceModel` constructor, or pass `allow_embedding_resizing=True` to have it done automatically.
```

## Expected behavior
It should not raise error.

## Additional context
Llamav2's tokenizer has `tokenizer.vocab_size == 32000` and `len(tokenizer) == 32001`, where the additional special token is the pad_token: https://huggingface.co/docs/transformers/main/model_doc/llama2.

As a quick workaround, editing the composer repo like https://github.com/es94129/composer/commit/4944b8187e43a0293e0e6ab2fcd8c7a753330e42 could enable `eval.py` to run and show reasonable evaluation results.

To really fix this problem, it might require passing `allow_embedding_resizing=True` to the `HuggingFaceModel` from the eval script.
