### ISSUE TITLE
'weight' must be 2-D with LLaMa family 

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#511]
My Llama trains ok with llm-foundry pipeline, but `generate` callback ruins this with error:

`'weight' must be 2-D`, more traceback below:

```
/usr/lib/python3/dist-packages/transformers/models/llama/modeling_llama.py:5 │
31 in forward                                                                │
                                                                             │
  528 │   │   │   position_ids = position_ids.view(-1, seq_length).long()    │
  529 │   │                                                                  │
  530 │   │   if inputs_embeds is None:                                      │
❱ 531 │   │   │   inputs_embeds = self.embed_tokens(input_ids)               │
  532 │   │   # embed positions                                              │
  533 │   │   if attention_mask is None:                                     │
  534 │   │   │   attention_mask = torch.ones(                               │
                                                                             │
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:1501 in _call_impl │
                                                                             │
  1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
  1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
  1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
  1502 │   │   # Do not call functions when jit is used                      │
  1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
  1504 │   │   backward_pre_hooks = []                                       │
                                                                             │
/usr/lib/python3/dist-packages/torch/nn/modules/sparse.py:162 in forward     │
                                                                             │
  159 │   │   │   │   self.weight[self.padding_idx].fill_(0)                 │
  160 │                                                                      │
  161 │   def forward(self, input: Tensor) -> Tensor:                        │
❱ 162 │   │   return F.embedding(                                            │
  163 │   │   │   input, self.weight, self.padding_idx, self.max_norm,       │
  164 │   │   │   self.norm_type, self.scale_grad_by_freq, self.sparse)      │
  165                                                                        │
                                                                             │
/usr/lib/python3/dist-packages/torch/nn/functional.py:2210 in embedding      │
                                                                             │
  2207 │   │   #   torch.embedding_renorm_                                   │
  2208 │   │   # remove once script supports set_grad_enabled                │
  2209 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type │
❱ 2210 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_ │
  2211                                                                       │
  2212                                                                       │
  2213 def embedding_bag(                                                    │
╰──────────────────────────────────────────────────────────────────────────────╯
'weight' must be 2-D
```

using this model config 

```
    model:
      name: hf_causal_lm
      pretrained_model_name_or_path: huggyllama/llama-7b
      pretrained: true
      force_download: true
      tie_word_embeddings: false

    # Tokenizer
    tokenizer:
      name: huggyllama/llama-7b
      kwargs:
        model_max_length: ${max_seq_len}
```

and this FSDP:

```
# FSDP
    fsdp_config:
      sharding_strategy: FULL_SHARD
      mixed_precision: PURE
      activation_checkpointing: true
      activation_checkpointing_reentrant: false
      activation_cpu_offload: false
      limit_all_gathers: true
      verbose: false
 ```
