### ISSUE TITLE
How do I train when I have multiple folders each having multiple .mds.zstd files?

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#552]
## How do I combine multiple mds shards?
I have multiple, say, 100 datasets of type **<class 'datasets.arrow_dataset.Dataset'>** .
hf_dataset_1 = Dataset.load_from_disk('path_1')
hf_dataset_2 = Dataset.load_from_disk('path_2')
hf_dataset_3 = Dataset.load_from_disk('path_3')
...
hf_dataset_100 = Dataset.load_from_disk('path_100')

Using convert_dataset_json.py, I get 100 corresponding folders, and each folder having multiple **.mds.zstd** files.

Now, how do I use all of those .mds.zstd files to do pretraining?

**Comment by palash04** [comment]
Or Is there any way to write **.mds.zstd files** in the same folder for different hf_datasets?

**Comment by palash04** [comment]
I found this issue https://github.com/mosaicml/llm-foundry/issues/426, which has streams incorporated in the yaml config.
Is there any doc/readme which says how to add config for streaming in the yaml?

**Comment by karan6181** [comment]
Hi @palash04, Streaming datasets are conceptually just a list of shards. The index file (index.json) contains the metadata for each shard, in order. You can merge them into a combined dataset at parent folder, let say, "dataset/" by creating a new combined index file like this at "dataset/index.json", Where your directory structure would look something like this below. Checkout [this](https://docs.mosaicml.com/projects/streaming/en/stable/examples/multiprocess_dataset_conversion.html#Merge-meta-data) script on how to do that.

```
dataset
├── index.json
├── path_1
│   ├── index.json
│   └── shard.00000.mds.zstd
├── path_2
│   ├── index.json
│   └── shard.00000.mds.zstd
└── path_100
    ├── index.json
    └── shard.00000.mds.zstd
```

**Comment by palash04** [comment]
Thanks @karan6181, I'll try this out.

**Comment by germanjke** [comment]
> Hi @palash04, Streaming datasets are conceptually just a list of shards. The index file (index.json) contains the metadata for each shard, in order. You can merge them into a combined dataset at parent folder, let say, "dataset/" by creating a new combined index file like this at "dataset/index.json", Where your directory structure would look something like this below. Checkout [this](https://docs.mosaicml.com/projects/streaming/en/stable/examples/multiprocess_dataset_conversion.html#Merge-meta-data) script on how to do that.
> 
> ```
> dataset
> ├── index.json
> ├── path_1
> │   ├── index.json
> │   └── shard.00000.mds.zstd
> ├── path_2
> │   ├── index.json
> │   └── shard.00000.mds.zstd
> └── path_100
>     ├── index.json
>     └── shard.00000.mds.zstd
> ```

hi @karan6181 

it's equilent to 

```
train_loader:
  name: text
  drop_last: true
  num_workers: 8
  dataset:
    eos_token_id: ${eos_token_id}
    max_seq_len: ${max_seq_len}
    num_canonical_nodes: ${num_canonical_nodes}
    shuffle: true
    shuffle_algo: py1b
    shuffle_seed: ${global_seed}
    streams:
      c4:
        local: /tmp/dataset/c4/
        repeat: 1.0
        remote: s3:/dataset/c4/
        split: train
      markdown:
        local: /tmp/dataset/markdown/
        repeat: 1.0
        remote: s3://dataset/markdown/
        split: null
```
? 

Can I merge in my train yaml with `repeat` parameter?
