### ISSUE TITLE
RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by karandua2016** [mosaicml/llm-foundry#777]
I am trying to train an MPT model using LLM Foundry on an A10 - 2 GPU machine. I know A10 is not officially supported, but would appreciate a solution if this issue has been seen before and can be resolved quickly.

I am getting an error: **`RuntimeError: Tensors must be CUDA and dense`**

Following are the primary libraries on my environment:

**CUDA: 11.7
Torch: 2.0.1+cu117
Transformers: 4.30.2**

**Comment by dakinggg** [comment]
We will need more information to help you. What are you trying to run?

**Comment by karandua2016** [comment]
I am trying to train an mpt-7b-instruct using llm foundry and composer, on an A10 server.

This is my configuration:

```
# max_seq_len: 6144
max_seq_len: 1
global_seed: 17

# Run Name
run_name: # If left blank, will be read from env var $RUN_NAME

model:
  name: hf_causal_lm
  pretrained: true
  pretrained_model_name_or_path: mosaicml/mpt-7b-instruct
  # init_device: meta
  config_overrides:
    max_seq_len: ${max_seq_len}
    attn_config:
      attn_impl: triton
      # Set this to `true` if using `train_loader.dataset.packing_ratio` below
      attn_uses_sequence_id: false

# Tokenizer
tokenizer:
  name: mosaicml/mpt-7b-instruct
  kwargs:
    model_max_length: ${max_seq_len}

# Local data to load into huggingface datasets
dataset: &hf_dataset
  hf_name: json
  max_seq_len: ${max_seq_len}
  allow_pad_trimming: false
  decoder_only_format: true
  shuffle: true
  

# Dataloaders
train_loader: &train_loader
  name: finetuning
  dataset:
    <<: *hf_dataset
    hf_kwargs:
        data_dir: /home/kadua/mpt-finetuning/datasets/abc/json-ds/train
    split: train
    
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0

eval_loader: &eval_loader
  name: finetuning
  dataset:
    <<: *hf_dataset
    hf_kwargs:
        data_dir: /home/kadua/mpt-finetuning/datasets/abc/json-ds/validation
    split: validation
    
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0

# Optimization
scheduler:
  name: linear_decay_with_warmup  # linear no warmup is HF default which dolly used
  t_warmup: 50ba  # add some warmup though, seems to help with MPT
  alpha_f: 0

optimizer:
  # Based on Dolly
  name: decoupled_adamw
  lr: 5.0e-6
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-8
  weight_decay: 0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 9ep  # 2-3 epochs seems like the sweet spot
eval_interval: 1ep
eval_subset_num_batches: -1
# eval_first: true
global_train_batch_size: 2  # somewhere in the 6-8 * numgpus range seems good

# System
seed: ${global_seed}
device_eval_batch_size: 1
# device_train_microbatch_size: 4
device_train_microbatch_size: 1
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: true
  limit_all_gathers: true
  verbose: false

# Logging
progress_bar: true
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

# loggers:
#   wandb: {}

# Checkpoint to local filesystem or remote object store
save_interval: 1ep
# save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
save_folder: /home/kadua/mpt-finetuning/finetuned-models/multitask-finetuning/{run_name}
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints
```
The only error that I get in my logs is `RuntimeError: Tensors must be CUDA and dense`
