### ISSUE TITLE
sharded model format

### ISSUE THREAD

**Issue by j-Gaow** [mosaicml/llm-foundry#840]
I'm tring to save sharded model in case of code termination with the following configuration:
```
# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: false
  state_dict_type: sharded
```
specified this in train.py
```
    save_filename: str = pop_config(
        cfg,
        'save_filename',
        must_exist=False,
        default_value='ep{epoch}-ba{batch}-rank{rank}.pt')
```
but it save it as __{rank}_0.distcp instead of ep{epoch}-ba{batch}-rank{rank}.pt format
##environment
torch                     2.1.1
transformers              4.36.2
cudatoolkit               11.3.1
composer               0.17.2
