### ISSUE TITLE
Triton attention patch from Mistral

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#860]
Hi!

I can use it for LLaMa like

```
# Model
model:
  name: hf_causal_lm
  model_type: llama
  attention_patch_type: triton
  pretrained_model_name_or_path: /Llama-2-7B
  pretrained: true
```

Can I use it to Mistral or it's not supported yet?
