### ISSUE TITLE
Evaluation result mismatch

### ISSUE THREAD

**Issue by congyingxia** [mosaicml/llm-foundry#88]
I tried to run the 0-shot evaluation on winograd for the MPT-7b model. This is the result that I got:
Eval metrics/winograd/0-shot/InContextLearningMultipleChoiceAccuracy: 0.5055

This is the script that I use:
python eval/eval.py \
  eval/yamls/hf_eval.yaml \
  icl_tasks=eval/yamls/winograd.yaml \
  model_name_or_path=mosaicml/mpt-7b

The reported number for 0-shot winograd for MPT-7b is 0.878. Is there anything missing here?

![image](https://github.com/mosaicml/llm-foundry/assets/26128195/026b5547-038d-4b91-b2b3-44a3a03212cc)

**Comment by bmosaicml** [comment]
I just had success running `composer eval/eval.p YAML_NAME.yaml`

with the following YAML:

```
seed: 1
  max_seq_len: 1024
  device_eval_batch_size: 4

  fsdp_config:
    mixed_precision: PURE
    sharding_strategy: FULL_SHARD
  icl_tasks:
    -
      label: winograd
      dataset_uri: eval/local_data/winograd_wsc.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot: [0, 1, 5, 10]
      icl_task_type: schema

  model:
      device: cpu
      name: hf_causal_lm
      pretrained: true
      pretrained_model_name_or_path: mosaicml/mpt-7b
      use_auth_token: false
  
  tokenizer:
      kwargs:
        model_max_length: ${max_seq_len}
      name: mosaicml/mpt-7b
```

Can you try this and let men now how it goes?
