### ISSUE TITLE
Finetune MPT models with  local dataset

### ISSUE THREAD

**Issue by arpitkk** [mosaicml/llm-foundry#94]
Hello Team,

Can you please guide on how to finetune on local datasets, the instructions given in scripts/train are not so clear. Below yaml file was given as sample example:

train_loader:
    name: finetuning
    dataset:
        hf_name: **my-local-dataset**
        hf_kwargs:
            data_files:
                train: /path/to/train.jsonl
        preprocessing_fn: my.import.path:my_preprocessing_fn
        split: train

So do we need to create a loading_script to load local dataset using huggingface datasets or is there a way we can directly use jsonl file paths instead of converting it into huggingface dataset & for that what changes I need to make in yaml file

**Comment by alextrott16** [comment]
Sorry for the lack of clarity here, we'll update the docs.

Going off of @arpitkk 's example, you would want to use `train_loader.dataset.hf_name: json` and keep the rest the same.

Just to clarify, that config will eventually influence the behavior of this dataset-building method here:https://github.com/mosaicml/llm-foundry/blob/6c16a6e9b31abe179dda7d71e9601f866721d6fa/llmfoundry/data/finetuning/tasks.py#L223

So, by setting your config to
```yaml
train_loader:
   name: finetuning
   dataset:
      hf_name: json
      hf_kwargs:
         data_files:
            train: /path/to/train.jsonl
      preprocessing_fn: my.import.path:my_preprocessing_fn
      split: train
```

The `build_from_hf` method will _effectively_ execute the following code:
```python
import datasets
from my.import.path import my_preprocessing_fn

dataset = datasets.load_dataset('json', split='train',  data_files={'train': '/path/to/train.jsonl'})

def dataset_mapper(example: Dict):
    example = my_preprocessing_fn(example)
    return _tokenize_formatted_example(example, tokenizer)

columns_to_remove = list(dataset[0].keys())
tokenized_dataset = dataset.map(
    dataset_mapper,
    batched=False,
    remove_columns=columns_to_remove,
)
```

Does that help to clear things up? If so, I can work a similar explanation into the README. If not, please let me know what still feels unclear!

**Comment by baptistejamin** [comment]
There might be an issue then. Here is the config I am using:

```
train_loader:
  name: finetuning

  dataset:
    hf_name: json
    hf_kwargs:
       data_files:
          train: /mnt/training/mylocaldataset/train.jsonl
    preprocessing_fn: mylocaldataset.utils:prep_fn
    split: train
    max_seq_len: ${max_seq_len}
    allow_pad_trimming: false
    decoder_only_format: true
    shuffle: true
````


I am running with: `composer llm-foundry/scripts/train/train.py   mpt.yml   save_folder=mpt-tuned` at the path `/mnt/training`.

wc -l /mnt/training/mylocaldataset/train.jsonl: 1212821

I will debug this today and let you know if I make some progress :)

**Comment by baptistejamin** [comment]
Issue found!

It seems there are a couple of bugs in the HuggingFace library. First, due to a regex problem the system is mixing the `train.jsonl` and the split `train`.

The detailed should not be named `train.jsonl`. Name it for instance `prompts.jsonl`.

Also, I now use data_dir instead and it works fine this way.

```
dataset:
    hf_name: json
    hf_kwargs:
      keep_in_memory: true
      data_dir: /mnt/training/mylocaldataset
    preprocessing_fn: mylocaldataset.utils:prep_fn
   ````
